from pathlib import Path
import re
import subprocess
import tempfile


def run(*args: str) -> None:
    subprocess.run(args, check=True)


capabilities = Path("backend/config/capabilities.json")
text = capabilities.read_text()
if '"symbolic_detail"' not in text:
    suffix = "\n    }\n  }\n}\n"
    if not text.endswith(suffix):
        raise RuntimeError("unexpected capabilities.json ending")
    block = '''
    },
    "symbolic_detail": {
      "status": "experimental",
      "input": "midi",
      "engine": "partitura_note_array_v1",
      "exposure": {"inspector": true, "annotations": false, "ask": false},
      "evaluation": {
        "dataset": "deterministic synthetic MIDI fixtures + repository real-stack transcription path",
        "metric": "experimental_product_integration",
        "details": "#1178: register, onset-centroid contour, inferred-voice interval motion, onset density, symbolic texture, and qualified inter-voice motion are computed from the exact source MIDI Version."
      },
      "validated_domain": "within-Version symbolic note-event measurement for midi_performance and midi_corrected sources",
      "notes": "Experimental Inspector detail only. Partitura may infer score voices during MIDI import; contour is an onset pitch-centroid proxy. Results are not canonical melody, counterpoint, voice-leading, form, audio texture, or theory truth, and are not admitted to Ask/annotations."
    }
  }
}
'''
    capabilities.write_text(text[: -len(suffix)] + block)

workflows = Path("backend/domain/api/workflows_jobs.py")
text = workflows.read_text()
pattern = re.compile(
    r"_PUBLIC_CREATE_WORKFLOW_ACTIONS = frozenset\(\s*\{([^}]*)\}\s*\)", re.S
)
match = pattern.search(text)
if not match:
    raise RuntimeError("public workflow allowlist not found")
actions = set(re.findall(r'"([^"]+)"', match.group(1)))
actions.add("symbolic_detail")
rendered = "_PUBLIC_CREATE_WORKFLOW_ACTIONS = frozenset(\n    {" + ", ".join(
    f'"{item}"' for item in sorted(actions)
) + "}\n)"
workflows.write_text(text[: match.start()] + rendered + text[match.end() :])

worker = Path("backend/worker.py")
text = worker.read_text()
import_line = "from domain.symbolic_detail_capability import register_symbolic_detail_capability\n"
if import_line not in text:
    anchor = "from domain.structure_map_capability import register_structure_map_capability\n"
    if anchor not in text:
        raise RuntimeError("worker import anchor not found")
    text = text.replace(anchor, anchor + import_line)
call = "    register_symbolic_detail_capability(worker)\n"
if call not in text:
    anchor = "    register_structure_map_capability(worker)\n"
    if anchor not in text:
        raise RuntimeError("worker registration anchor not found")
    text = text.replace(anchor, anchor + call)
worker.write_text(text)

session = Path("components/workspace/WorkspaceSession.tsx")
text = session.read_text()
set_decl = (
    'const OPTIONAL_ANALYSIS_CAPABILITIES = new Set(["structure_map", "melody_audition", "symbolic_detail"]);\n'
)
if "OPTIONAL_ANALYSIS_CAPABILITIES" not in text:
    anchor = 'const ACTIVE_JOB_STATES = new Set(["queued", "claimed", "running"]);\n'
    if anchor not in text:
        raise RuntimeError("WorkspaceSession constants anchor not found")
    text = text.replace(anchor, anchor + set_decl)
old = '''const latestJob = bundle.jobs.find((job) => (
        job.capability.name !== "structure_map"
        && job.capability.name !== "melody_audition"
      ));'''
new = '''const latestJob = bundle.jobs.find(
        (job) => !OPTIONAL_ANALYSIS_CAPABILITIES.has(job.capability.name),
      );'''
if old in text:
    text = text.replace(old, new, 1)
elif "!OPTIONAL_ANALYSIS_CAPABILITIES.has(job.capability.name)" not in text:
    raise RuntimeError("WorkspaceSession latest-job seam not found")
session.write_text(text)

run("python3", "-m", "pip", "install", "--disable-pip-version-check", "-q", "ruff==0.15.2")
run("ruff", "format", "backend/domain/api/workflows_jobs.py", "backend/worker.py")
run("npm", "ci")

with tempfile.TemporaryDirectory() as tmp:
    mmd = Path(tmp) / "frontend-dependencies.mmd"
    run(
        "npx",
        "--yes",
        "--package=dependency-cruiser@18.2.0",
        "--package=typescript@5.7.3",
        "depcruise",
        "--config",
        ".dependency-cruiser.cjs",
        "--output-type",
        "mermaid",
        "--include-only",
        "^(app|components|lib)/",
        "--collapse",
        "2",
        "--output-to",
        str(mmd),
        "app",
        "components",
        "lib",
    )
    header = """# Frontend dependency graph

> Generated by dependency-cruiser 18.2.0 with TypeScript 5.7.3 from `.dependency-cruiser.cjs`. Do not hand-edit this graph; regenerate it through the architecture check when frontend imports change.

This is an orientation view of `app/`, `components/`, and `lib/`. Deeper folders are collapsed to keep the graph reviewable. The architecture rules in `.dependency-cruiser.cjs`, not the picture alone, are the enforceable contract.

```mermaid
"""
    Path("docs/generated/frontend-dependencies.md").write_text(
        header + mmd.read_text() + "```\n"
    )
