from pathlib import Path
import re
import subprocess
import tempfile


def run(*args: str) -> None:
    subprocess.run(args, check=True)


capabilities = Path("backend/config/capabilities.json")
text = capabilities.read_text()
if '"production_spatial"' not in text:
    suffix = "\n    }\n  }\n}\n"
    if not text.endswith(suffix):
        raise RuntimeError("unexpected capabilities.json ending")
    block = '''
    },
    "production_spatial": {
      "status": "experimental",
      "input": "audio",
      "engine": "pyloudnorm_librosa_mid_side_v1",
      "exposure": {"inspector": true, "annotations": false, "ask": false},
      "evaluation": {
        "dataset": "synthetic stereo/mono fixtures",
        "metric": "experimental_product_integration",
        "details": "#1179: BS.1770 loudness, exact two-channel mid/side energy share, spectral centroid, and onset-strength changes are exposed only as method-qualified within-recording adjacent-window relations."
      },
      "validated_domain": "within-recording adjacent fixed-window measurement comparison",
      "notes": "Experimental opt-in Inspector lens only. Literal measurements and relations; no semantic timbre, mix-quality, width-quality, section, cause, importance, or cross-recording claims. Mid/side relation is unavailable unless the source is exactly stereo."
    }
  }
}
'''
    capabilities.write_text(text[: -len(suffix)] + block)

workflows = Path("backend/domain/api/workflows_jobs.py")
text = workflows.read_text()
pattern = re.compile(
    r"_PUBLIC_CREATE_WORKFLOW_ACTIONS = frozenset\(\s*\{([^}]*)\}\s*\)", re.S
)
match = pattern.search(text)
if not match:
    raise RuntimeError("public workflow allowlist not found")
actions = set(re.findall(r'"([^"]+)"', match.group(1)))
actions.add("production_spatial")
rendered = "_PUBLIC_CREATE_WORKFLOW_ACTIONS = frozenset(\n    {" + ", ".join(
    f'"{item}"' for item in sorted(actions)
) + "}\n)"
workflows.write_text(text[: match.start()] + rendered + text[match.end() :])

worker = Path("backend/worker.py")
text = worker.read_text()
import_line = (
    "from domain.production_spatial_capability import register_production_spatial_capability\n"
)
if import_line not in text:
    anchor = "from domain.pgmq_job_worker import PgmqJobWorker\n"
    if anchor not in text:
        raise RuntimeError("worker import anchor not found")
    text = text.replace(anchor, anchor + import_line)
call = "    register_production_spatial_capability(worker)\n"
if call not in text:
    anchor = "    register_structure_map_capability(worker)\n"
    if anchor not in text:
        raise RuntimeError("worker registration anchor not found")
    text = text.replace(anchor, anchor + call)
worker.write_text(text)

public_dispatch_test = Path("backend/tests/test_public_workflow_dispatch.py")
text = public_dispatch_test.read_text()
if '"production_spatial"' not in text:
    updated = text.replace(
        '"structure_map", "pitch_contour"],',
        '"structure_map", "pitch_contour", "production_spatial"],',
        1,
    )
    if updated == text:
        raise RuntimeError("public dispatch test anchor not found")
    public_dispatch_test.write_text(updated)

run("python3", "-m", "pip", "install", "--disable-pip-version-check", "-q", "ruff==0.15.2")
run(
    "ruff",
    "format",
    "backend/domain/api/workflows_jobs.py",
    "backend/worker.py",
    "backend/tests/test_public_workflow_dispatch.py",
)
run("npm", "ci")

with tempfile.TemporaryDirectory() as tmp:
    mmd = Path(tmp) / "frontend-dependencies.mmd"
    run(
        "npx",
        "--yes",
        "--package=dependency-cruiser@18.2.0",
        "--package=typescript@5.7.3",
        "depcruise",
        "--config",
        ".dependency-cruiser.cjs",
        "--output-type",
        "mermaid",
        "--include-only",
        "^(app|components|lib)/",
        "--collapse",
        "2",
        "--output-to",
        str(mmd),
        "app",
        "components",
        "lib",
    )
    header = """# Frontend dependency graph

> Generated by dependency-cruiser 18.2.0 with TypeScript 5.7.3 from `.dependency-cruiser.cjs`. Do not hand-edit this graph; regenerate it through the architecture check when frontend imports change.

This is an orientation view of `app/`, `components/`, and `lib/`. Deeper folders are collapsed to keep the graph reviewable. The architecture rules in `.dependency-cruiser.cjs`, not the picture alone, are the enforceable contract.

```mermaid
"""
    Path("docs/generated/frontend-dependencies.md").write_text(
        header + mmd.read_text() + "```\n"
    )
