/**
 * Deterministic temporal findings — musically meaningful observations
 * derived from existing analysis evidence.
 *
 * These are NOT generated by an LLM. They are deterministic transformations
 * of rhythm_density, rhythm_rests, and chord evidence.
 *
 * Each finding has:
 * - kind: category of observation
 * - start/end: time span
 * - label: human-readable observation
 * - evidence: deterministic source data
 */

import type { Insight } from "@/lib/domain.types";
import { formatTime } from "@/lib/format";

export interface TemporalFinding {
  id: string;
  kind: "density_peak" | "density_valley" | "rest" | "harmonic_activity";
  category: "rhythm" | "harmony";
  startSeconds: number;
  endSeconds: number;
  label: string;
  evidence: Record<string, unknown>;
}

/**
 * Derive a small number of meaningful temporal findings from existing insights.
 * Returns approximately 3-8 findings for an ordinary piece.
 */
export function deriveFindings(insights: Insight[]): TemporalFinding[] {
  const findings: TemporalFinding[] = [];

  // Rhythm findings from rhythm_density
  const densityInsights = insights.filter((i) => i.kind === "rhythm_density");
  for (const insight of densityInsights) {
    const windows = extractDensityWindows(insight);
    if (windows.length >= 2) {
      // Peak density
      const peak = windows.reduce((max, w) => w.density > max.density ? w : max, windows[0]);
      if (peak.density > 0) {
        findings.push({
          id: `density-peak-${insight.id}`,
          kind: "density_peak",
          category: "rhythm",
          startSeconds: peak.start,
          endSeconds: peak.end,
          label: `Peak note density around ${formatTime(peak.start)}`,
          evidence: { density: peak.density, windowStart: peak.start, windowEnd: peak.end },
        });
      }

      // Valley density (lowest non-zero)
      const nonZero = windows.filter((w) => w.density > 0);
      if (nonZero.length > 0) {
        const valley = nonZero.reduce((min, w) => w.density < min.density ? w : min, nonZero[0]);
        // Only add if valley is significantly different from peak
        if (valley.density < peak.density * 0.5) {
          findings.push({
            id: `density-valley-${insight.id}`,
            kind: "density_valley",
            category: "rhythm",
            startSeconds: valley.start,
            endSeconds: valley.end,
            label: `Quieter passage around ${formatTime(valley.start)}`,
            evidence: { density: valley.density, windowStart: valley.start, windowEnd: valley.end },
          });
        }
      }
    }
  }

  // Rest findings from rhythm_rests
  const restInsights = insights.filter((i) => i.kind === "rhythm_rests");
  for (const insight of restInsights) {
    const rests = extractRestSegments(insight);
    if (rests.length > 0) {
      // Longest rest
      const longest = rests.reduce((max, r) => r.duration > max.duration ? r : max, rests[0]);
      if (longest.duration >= 0.5) { // Only mention rests >= 500ms
        findings.push({
          id: `rest-${insight.id}`,
          kind: "rest",
          category: "rhythm",
          startSeconds: longest.start,
          endSeconds: longest.end,
          label: `Pronounced rest around ${formatTime(longest.start)}`,
          evidence: { duration: longest.duration, start: longest.start, end: longest.end },
        });
      }
    }
  }

  // Harmonic activity from chord changes
  const chordInsights = insights.filter((i) => i.kind === "chord");
  if (chordInsights.length >= 4) {
    // Find the most active passage (most chord changes in a sliding window)
    const sortedChords = chordInsights
      .filter((i) => i.span.start_seconds != null)
      .sort((a, b) => a.span.start_seconds! - b.span.start_seconds!);

    if (sortedChords.length >= 3) {
      // Use a window of ~4 chords to find most active passage
      let maxDensity = 0;
      let maxStart = 0;
      let maxEnd = 0;

      for (let i = 0; i <= sortedChords.length - 3; i++) {
        const windowStart = sortedChords[i].span.start_seconds!;
        const windowEnd = sortedChords[i + 2].span.end_seconds ?? sortedChords[i + 2].span.start_seconds! + 2;
        const windowDuration = windowEnd - windowStart;
        if (windowDuration > 0) {
          const density = 3 / windowDuration; // chords per second
          if (density > maxDensity) {
            maxDensity = density;
            maxStart = windowStart;
            maxEnd = windowEnd;
          }
        }
      }

      // Also find the least active passage
      let minDensity = Infinity;
      let minStart = 0;
      let minEnd = 0;

      for (let i = 0; i <= sortedChords.length - 3; i++) {
        const windowStart = sortedChords[i].span.start_seconds!;
        const windowEnd = sortedChords[i + 2].span.end_seconds ?? sortedChords[i + 2].span.start_seconds! + 2;
        const windowDuration = windowEnd - windowStart;
        if (windowDuration > 0) {
          const density = 3 / windowDuration;
          if (density < minDensity) {
            minDensity = density;
            minStart = windowStart;
            minEnd = windowEnd;
          }
        }
      }

      // Only add if there's a meaningful difference
      if (maxDensity > 0 && minDensity < Infinity && maxDensity > minDensity * 1.5) {
        findings.push({
          id: "harmonic-activity-peak",
          kind: "harmonic_activity",
          category: "harmony",
          startSeconds: maxStart,
          endSeconds: maxEnd,
          label: `Harmonic changes become more frequent around ${formatTime(maxStart)}`,
          evidence: { chordDensity: maxDensity, windowStart: maxStart, windowEnd: maxEnd },
        });
      }
    }
  }

  // Sort by time and limit to 8 findings
  findings.sort((a, b) => a.startSeconds - b.startSeconds);
  return findings.slice(0, 8);
}

function extractDensityWindows(insight: Insight): { start: number; end: number; density: number }[] {
  const windows = (insight.evidence?.windows ?? []) as {
    start?: number;
    end?: number;
    density?: number;
  }[];
  return windows
    .filter((w) => w.start != null && w.end != null && w.density != null)
    .map((w) => ({
      start: w.start!,
      end: w.end!,
      density: w.density!,
    }));
}

function extractRestSegments(insight: Insight): { start: number; end: number; duration: number }[] {
  const rests = (insight.evidence?.rests ?? []) as {
    start?: number;
    end?: number;
    duration?: number;
  }[];
  return rests
    .filter((r) => r.start != null && r.end != null)
    .map((r) => ({
      start: r.start!,
      end: r.end!,
      duration: r.duration ?? r.end! - r.start!,
    }));
}
