/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Ask */
        post: operations["create_ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/artifacts/finalize-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Upload */
        post: operations["finalize_upload_api_v1_projects__project_id__artifacts_finalize_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/artifacts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Artifact */
        post: operations["upload_artifact_api_v1_projects__project_id__artifacts_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/artifacts/upload-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Intent */
        post: operations["create_upload_intent_api_v1_projects__project_id__artifacts_upload_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Works */
        get: operations["list_works_api_v1_projects__project_id__works_get"];
        put?: never;
        /** Create Work */
        post: operations["create_work_api_v1_projects__project_id__works_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version Resource */
        get: operations["get_version_resource_api_v1_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{version_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entities */
        get: operations["list_entities_api_v1_versions__version_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{version_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_api_v1_versions__version_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analyze Workflow */
        post: operations["create_analyze_workflow_api_v1_workflows_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Compare Workflow */
        post: operations["create_compare_workflow_api_v1_workflows_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Correct Workflow */
        post: operations["create_correct_workflow_api_v1_workflows_correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Create Workflow */
        post: operations["create_create_workflow_api_v1_workflows_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Score Workflow
         * @description Rebuild Score from an existing canonical performance-MIDI version.
         *
         *     This route intentionally queues only the score capability. It never
         *     retranscribes audio, so changing Score interpretation does not mutate or
         *     replace the canonical performance representation used by Piano Roll.
         */
        post: operations["create_score_workflow_api_v1_workflows_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/understand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Understand Workflow */
        post: operations["create_understand_workflow_api_v1_workflows_understand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/variation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Variation Workflow
         * @description Queue an idempotent, complete transposed take from a MIDI version.
         */
        post: operations["create_variation_workflow_api_v1_workflows_variation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Work Bundle
         * @description Return a work and its complete immutable artifact/version graph.
         */
        get: operations["get_work_bundle_api_v1_works__work_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Work
         * @description Delete a work and its artifacts, versions, and storage objects.
         */
        delete: operations["delete_work_api_v1_works__work_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{work_id}/relations/measured-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Measured Changes
         * @description Return a bounded experimental top set from exact persisted evidence.
         */
        get: operations["measured_changes_api_v1_works__work_id__relations_measured_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{work_id}/relations/perceptual-span-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Perceptual Spans
         * @description Compare two user-selected spans using persisted, lineage-checked evidence.
         */
        post: operations["compare_perceptual_spans_api_v1_works__work_id__relations_perceptual_span_comparison_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Queue */
        get: operations["health_queue_health_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeWorkflowBody */
        AnalyzeWorkflowBody: {
            /** Project Id */
            project_id: string;
            /** Version Id */
            version_id: string;
        };
        /** Artifact */
        Artifact: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            kind: components["schemas"]["ArtifactKind"];
            /**
             * Mime Type
             * @default application/octet-stream
             */
            mime_type: string;
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
        };
        /**
         * ArtifactKind
         * @enum {string}
         */
        ArtifactKind: "audio_original" | "audio_enhanced" | "audio_rendered" | "midi_performance" | "midi_corrected" | "musicxml_score" | "rendered_score" | "stems" | "analysis_report";
        /** AskContext */
        AskContext: {
            /**
             * Currenttime
             * @default 0
             */
            currentTime: number;
            /** Playbacksourceid */
            playbackSourceId?: string | null;
            /**
             * Representationid
             * @enum {string}
             */
            representationId: "listen" | "piano_roll" | "score";
            selection?: components["schemas"]["AskSelection"] | null;
            /** Visibleinsights */
            visibleInsights?: components["schemas"]["AskVisibleInsight"][];
            /**
             * Workid
             * Format: uuid
             */
            workId: string;
        };
        /**
         * AskInsight
         * @description The subset of an `Insight` the explainer needs.
         *
         *     The frontend sends the full insight object; unknown extra fields (created_at,
         *     evidence, provenance, confidence, ...) are tolerated but not surfaced to the
         *     model, so no arbitrary database rows leak into the prompt.
         */
        AskInsight: {
            /** Claim */
            claim: string;
            /** Entity Ids */
            entity_ids?: string[];
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            span?: components["schemas"]["AskInsightSpan"];
            /** Version Id */
            version_id: string;
        };
        /** AskInsightReference */
        AskInsightReference: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "insight";
        };
        /** AskInsightSpan */
        AskInsightSpan: {
            /** End Beat */
            end_beat?: number | null;
            /** End Measure */
            end_measure?: number | null;
            /** End Seconds */
            end_seconds?: number | null;
            /** Start Beat */
            start_beat?: number | null;
            /** Start Measure */
            start_measure?: number | null;
            /** Start Seconds */
            start_seconds?: number | null;
        };
        /** AskLoopAction */
        AskLoopAction: {
            /**
             * Domain
             * @enum {string}
             */
            domain: "performance" | "notation";
            /** End */
            end: number;
            /** Start */
            start: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "loop";
        };
        /** AskMeasureReference */
        AskMeasureReference: {
            /** End */
            end?: number | null;
            /** Start */
            start: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "measure";
        };
        /** AskNotesReference */
        AskNotesReference: {
            /** Ids */
            ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "notes";
        };
        /** AskRequest */
        AskRequest: {
            context: components["schemas"]["AskContext"];
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** References */
            references?: (components["schemas"]["AskTimeReference"] | components["schemas"]["AskMeasureReference"] | components["schemas"]["AskNotesReference"] | components["schemas"]["AskInsightReference"])[];
            /** Suggestedactions */
            suggestedActions?: (components["schemas"]["AskSeekAction"] | components["schemas"]["AskLoopAction"] | components["schemas"]["AskShowRepresentationAction"])[] | null;
        };
        /** AskSeekAction */
        AskSeekAction: {
            /**
             * Domain
             * @enum {string}
             */
            domain: "performance" | "notation";
            /** Seconds */
            seconds: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "seek";
        };
        /**
         * AskSelection
         * @description Mirror of the frontend `MusicalSelection` (all fields optional).
         */
        AskSelection: {
            measureRange?: components["schemas"]["AskSelectionMeasureRange"] | null;
            /** Noteids */
            noteIds?: string[] | null;
            provenance?: components["schemas"]["AskSelectionProvenance"] | null;
            timeRange?: components["schemas"]["AskSelectionTimeRange"] | null;
        };
        /** AskSelectionMeasureRange */
        AskSelectionMeasureRange: {
            /** End */
            end: number;
            /** Start */
            start: number;
        };
        /** AskSelectionProvenance */
        AskSelectionProvenance: {
            /** Measureapproximate */
            measureApproximate: boolean;
            /**
             * Origin
             * @enum {unknown}
             */
            origin: "waveform" | "piano_roll" | "score" | null;
            /** Timeexact */
            timeExact: boolean;
        };
        /** AskSelectionTimeRange */
        AskSelectionTimeRange: {
            /**
             * Domain
             * @enum {string}
             */
            domain: "performance" | "notation";
            /** End */
            end: number;
            /** Start */
            start: number;
        };
        /** AskShowRepresentationAction */
        AskShowRepresentationAction: {
            /** Representationid */
            representationId: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "show_representation";
        };
        /** AskTimeReference */
        AskTimeReference: {
            /**
             * Domain
             * @enum {string}
             */
            domain: "performance" | "notation";
            /** End */
            end?: number | null;
            /** Start */
            start: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "time";
        };
        /** AskVisibleInsight */
        AskVisibleInsight: {
            /**
             * Category
             * @enum {string}
             */
            category: "selection" | "whole-work";
            insight: components["schemas"]["AskInsight"];
        };
        /** Body_upload_artifact_api_v1_projects__project_id__artifacts_upload_post */
        Body_upload_artifact_api_v1_projects__project_id__artifacts_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Work Id */
            work_id?: string | null;
        };
        /** Cadence */
        Cadence: {
            /** Chords */
            chords?: string[];
            /** Kind */
            kind: string;
            /** Position Seconds */
            position_seconds: number;
        };
        /** Capability */
        Capability: {
            /** Accepted Input Kinds */
            accepted_input_kinds?: components["schemas"]["ArtifactKind"][];
            /** Failure Modes */
            failure_modes?: string[];
            /** Name */
            name: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Produces Output Kinds */
            produces_output_kinds?: components["schemas"]["ArtifactKind"][];
            /** Version */
            version: string;
        };
        /** ChordEntity */
        ChordEntity: {
            /** Bass */
            bass?: string | null;
            /** End Seconds */
            end_seconds: number;
            /** Quality */
            quality: string;
            /** Root */
            root: string;
            /** Start Seconds */
            start_seconds: number;
        };
        /** CompareWorkflowBody */
        CompareWorkflowBody: {
            /** Project Id */
            project_id: string;
            /** Version Id A */
            version_id_a: string;
            /** Version Id B */
            version_id_b: string;
        };
        /** CorrectWorkflowBody */
        CorrectWorkflowBody: {
            /** Corrected Notes */
            corrected_notes: {
                [key: string]: unknown;
            }[];
            /** Project Id */
            project_id: string;
            /** Selection End */
            selection_end?: number | null;
            /** Selection Start */
            selection_start?: number | null;
            /** Version Id */
            version_id: string;
        };
        /** CreateProjectBody */
        CreateProjectBody: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** CreateUploadIntentBody */
        CreateUploadIntentBody: {
            /** Byte Size */
            byte_size: number;
            /** Content Type */
            content_type?: string | null;
            /** Filename */
            filename: string;
            /** Work Id */
            work_id?: string | null;
        };
        /** CreateWorkBody */
        CreateWorkBody: {
            /** Composer */
            composer?: string | null;
            /** Title */
            title: string;
        };
        /** CreateWorkflowBody */
        CreateWorkflowBody: {
            /**
             * Action
             * @default transform
             */
            action: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id: string;
            /** Version Id */
            version_id: string;
        };
        /** DeletedWorkResponse */
        DeletedWorkResponse: {
            /** Deleted */
            deleted: string;
        };
        /** Entity */
        Entity: {
            cadence?: components["schemas"]["Cadence"] | null;
            chord?: components["schemas"]["ChordEntity"] | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            kind: components["schemas"]["EntityKind"];
            /**
             * Label
             * @default
             */
            label: string;
            note?: components["schemas"]["NoteEntity"] | null;
            span?: components["schemas"]["Span"];
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
        /**
         * EntityKind
         * @enum {string}
         */
        EntityKind: "note" | "chord" | "beat" | "measure" | "phrase" | "section" | "cadence" | "motif";
        /**
         * EvidenceRef
         * @description #371-compatible namespaced reference to one series inside an analysis report.
         */
        EvidenceRef: {
            /** Id */
            id: string;
            /**
             * Namespace
             * @default perceptual_series
             * @constant
             */
            namespace: "perceptual_series";
            /**
             * Type
             * @default external
             * @constant
             */
            type: "external";
        };
        /** FinalizeUploadBody */
        FinalizeUploadBody: {
            /** Byte Size */
            byte_size: number;
            /** Content Type */
            content_type?: string | null;
            /** Filename */
            filename: string;
            /** Storage Key */
            storage_key: string;
            /** Work Id */
            work_id?: string | null;
        };
        /**
         * GroundedFindingMeasurement
         * @description One user-facing literal clause tied to the exact evidence reference.
         */
        GroundedFindingMeasurement: {
            /** Comparison Value */
            comparison_value: number | number[];
            /** Components */
            components?: string[];
            /** Delta */
            delta: number | number[];
            /**
             * Direction
             * @enum {string}
             */
            direction: "higher" | "lower" | "mixed" | "unchanged";
            /**
             * Feature
             * @enum {string}
             */
            feature: "rms" | "spectral_centroid" | "relative_band_energy" | "onset_strength";
            /** Normalization */
            normalization: string;
            /** Subject Value */
            subject_value: number | number[];
            /** Summary */
            summary: string;
            support_ref: components["schemas"]["EvidenceRef"];
            /** Unit */
            unit: string | null;
        };
        /**
         * GroundedRelationFinding
         * @description Relation-first product finding with enough support to audit every clause.
         */
        GroundedRelationFinding: {
            /** Available Actions */
            available_actions: ("focus" | "compare" | "evidence")[];
            comparison_locator: components["schemas"]["SecondsSpanLocator"];
            /** Evidence Summary */
            evidence_summary: string;
            /** Headline */
            headline: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @default perceptual_span_comparison
             * @constant
             */
            kind: "perceptual_span_comparison";
            /**
             * Maturity
             * @default production
             * @constant
             */
            maturity: "production";
            /** Measurements */
            measurements: components["schemas"]["GroundedFindingMeasurement"][];
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
            /**
             * Relation Kind
             * @default compare
             * @constant
             */
            relation_kind: "compare";
            /**
             * Source Relation Id
             * Format: uuid
             */
            source_relation_id: string;
            subject_locator: components["schemas"]["SecondsSpanLocator"];
            sufficiency: components["schemas"]["RelationSufficiency"];
            /** Support Refs */
            support_refs: components["schemas"]["EvidenceRef"][];
            /**
             * Trust Class
             * @default deterministic_derived
             * @constant
             */
            trust_class: "deterministic_derived";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthLiveResponse */
        HealthLiveResponse: {
            /** Release */
            release: string;
            /**
             * Status
             * @constant
             */
            status: "alive";
        };
        /** HealthQueueResponse */
        HealthQueueResponse: {
            /** Heartbeat Source */
            heartbeat_source?: string | null;
            /** Queued */
            queued: number;
            /** Reason */
            reason?: string | null;
            /** Running */
            running: number;
            /** Stale Leases */
            stale_leases: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
            /** Workers */
            workers: number;
        };
        /** HealthReadyResponse */
        HealthReadyResponse: {
            /** Database */
            database: boolean;
            /** Reason */
            reason?: string | null;
            /** Release */
            release: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
            /** Storage */
            storage: boolean;
            /** Supabase */
            supabase: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Insight */
        Insight: {
            /** Claim */
            claim: string;
            /** Confidence */
            confidence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By */
            created_by?: string | null;
            /** Entity Ids */
            entity_ids?: string[];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Kind */
            kind: string;
            /** Produced By Job Id */
            produced_by_job_id?: string | null;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
            span?: components["schemas"]["Span"];
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
        /** Job */
        Job: {
            /** Cache Key */
            cache_key?: string | null;
            capability: components["schemas"]["Capability"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By */
            created_by?: string | null;
            /** Error */
            error?: string | null;
            /** Error Details */
            error_details?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Input Version Ids */
            input_version_ids?: string[];
            lifecycle?: components["schemas"]["JobLifecycle"];
            /** Output Version Ids */
            output_version_ids?: string[];
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
            /**
             * Workflow Id
             * Format: uuid
             */
            workflow_id: string;
        };
        /** JobLifecycle */
        JobLifecycle: {
            /** Completed At */
            completed_at?: string | null;
            /** @default queued */
            current: components["schemas"]["JobStage"];
            /** Lease Expires At */
            lease_expires_at?: string | null;
            /**
             * Max Retries
             * @default 3
             */
            max_retries: number;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /** Stages */
            stages?: components["schemas"]["ProcessingStatus"][];
            /** Started At */
            started_at?: string | null;
        };
        /**
         * JobStage
         * @enum {string}
         */
        JobStage: "queued" | "claimed" | "running" | "succeeded" | "failed" | "cancelled";
        /** JobStateResponse */
        JobStateResponse: {
            /** Capability */
            capability: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Input Version Ids */
            input_version_ids: string[];
            /** Message */
            message: string;
            /** Output Version Ids */
            output_version_ids: string[];
            /** Progress */
            progress: number;
            stage: components["schemas"]["JobStage"];
            /** Workflow Id */
            workflow_id: string;
        };
        /**
         * MeasuredChangeCandidate
         * @description One bounded experimental candidate with production-owned literal evidence.
         */
        MeasuredChangeCandidate: {
            /** After Span Seconds */
            after_span_seconds: [
                number,
                number
            ];
            /** Before Span Seconds */
            before_span_seconds: [
                number,
                number
            ];
            /**
             * Boundary Seconds
             * @description Shared edge between the candidate's before/after comparison windows; a listening-navigation anchor, not an estimate of the physical transition instant.
             */
            boundary_seconds: number;
            /** Changed Component Count */
            changed_component_count: number;
            /** Changed Feature Count */
            changed_feature_count: number;
            finding: components["schemas"]["GroundedRelationFinding"];
            /** Normalized Component Changes */
            normalized_component_changes?: {
                [key: string]: number;
            };
            /** Normalized Feature Changes */
            normalized_feature_changes?: {
                [key: string]: number;
            };
            /** Rank */
            rank: number;
            /** Ranking Score */
            ranking_score: number;
        };
        /**
         * MeasuredChangeQueryResult
         * @description Truthful availability/result state for experimental measured changes.
         */
        MeasuredChangeQueryResult: {
            /** Candidates */
            candidates?: components["schemas"]["MeasuredChangeCandidate"][];
            /** Evidence Report Version Id */
            evidence_report_version_id?: string | null;
            /** Method */
            method?: string | null;
            /** Method Parameters */
            method_parameters?: {
                [key: string]: number;
            };
            /** Reasons */
            reasons?: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "unavailable" | "withheld" | "failed";
        };
        /** NoteEntity */
        NoteEntity: {
            /** Amplitude */
            amplitude?: number | null;
            /** End Seconds */
            end_seconds: number;
            /** Pitch */
            pitch: number;
            /** Start Seconds */
            start_seconds: number;
            /**
             * Velocity
             * @default 64
             */
            velocity: number;
            /**
             * Voice
             * @default 0
             */
            voice: number;
        };
        /**
         * PerceptualSpanComparisonBody
         * @description Compare two explicit seconds-authoritative spans in one audio Version.
         */
        PerceptualSpanComparisonBody: {
            /** Comparison End Seconds */
            comparison_end_seconds: number;
            /** Comparison Start Seconds */
            comparison_start_seconds: number;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /** Subject End Seconds */
            subject_end_seconds: number;
            /** Subject Start Seconds */
            subject_start_seconds: number;
        };
        /** PerceptualSpanComparisonResponse */
        PerceptualSpanComparisonResponse: {
            /** Evidence Report Version Id */
            evidence_report_version_id?: string | null;
            finding?: components["schemas"]["GroundedRelationFinding"] | null;
            /** Reasons */
            reasons?: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "unavailable" | "withheld" | "failed";
        };
        /** ProcessingStatus */
        ProcessingStatus: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            stage: components["schemas"]["JobStage"];
            /** Started At */
            started_at?: string | null;
        };
        /** Project */
        Project: {
            /** Archived At */
            archived_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Name */
            name: string;
            /** Owner Id */
            owner_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** RelationSufficiency */
        RelationSufficiency: {
            /**
             * Gate
             * @default USER_SELECTION_CAN_SUBSTITUTE_STRUCTURE
             * @constant
             */
            gate: "USER_SELECTION_CAN_SUBSTITUTE_STRUCTURE";
            /** Reasons */
            reasons?: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "experimental" | "withhold";
        };
        /** ScoreWorkflowBody */
        ScoreWorkflowBody: {
            /** Performance Midi Version Id */
            performance_midi_version_id: string;
            /** Project Id */
            project_id: string;
            /** Score Engine */
            score_engine?: ("musescore" | "pm2s") | null;
        };
        /**
         * SecondsSpanLocator
         * @description Seconds-authoritative span whose validity is decided by sufficiency logic.
         */
        SecondsSpanLocator: {
            /**
             * Authority
             * @default explicit
             * @enum {string}
             */
            authority: "explicit" | "user_selected" | "trusted";
            /** End Seconds */
            end_seconds: number;
            /**
             * Source Artifact Version Id
             * Format: uuid
             */
            source_artifact_version_id: string;
            /** Start Seconds */
            start_seconds: number;
        };
        /** Span */
        Span: {
            /** End Beat */
            end_beat?: number | null;
            /** End Measure */
            end_measure?: number | null;
            /** End Seconds */
            end_seconds?: number | null;
            /** Start Beat */
            start_beat?: number | null;
            /** Start Measure */
            start_measure?: number | null;
            /** Start Seconds */
            start_seconds?: number | null;
        };
        /** UnderstandWorkflowBody */
        UnderstandWorkflowBody: {
            /** Project Id */
            project_id: string;
            /** Score Engine */
            score_engine?: ("musescore" | "pm2s") | null;
            /** Transcription Profile */
            transcription_profile?: ("auto" | "solo_piano") | null;
            /** Version Id */
            version_id: string;
        };
        /** UploadArtifactResponse */
        UploadArtifactResponse: {
            artifact: components["schemas"]["Artifact"];
            version: components["schemas"]["Version"];
        };
        /** UploadIntentResponse */
        UploadIntentResponse: {
            /** Bucket */
            bucket: string;
            /** Max Bytes */
            max_bytes: number;
            /** Storage Key */
            storage_key: string;
            /** Token */
            token: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariationWorkflowBody */
        VariationWorkflowBody: {
            /** Project Id */
            project_id: string;
            /** Transpose Semitones */
            transpose_semitones: number;
            /** Version Id */
            version_id: string;
        };
        /** Version */
        Version: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Byte Size */
            byte_size?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By */
            created_by?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Lineage */
            lineage?: string[];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Parent Version Id */
            parent_version_id?: string | null;
            /** Produced By Job Id */
            produced_by_job_id?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /** Storage Bucket */
            storage_bucket: string;
            /** Storage Key */
            storage_key: string;
        };
        /** VersionResourceResponse */
        VersionResourceResponse: {
            artifact: components["schemas"]["Artifact"];
            /** Signed Url */
            signed_url: string;
            version: components["schemas"]["Version"];
        };
        /** Work */
        Work: {
            /** Composer */
            composer?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** WorkArtifactBundleResponse */
        WorkArtifactBundleResponse: {
            artifact: components["schemas"]["Artifact"];
            latest_version?: components["schemas"]["Version"] | null;
            /** Signed Url */
            signed_url?: string | null;
            /** Versions */
            versions: components["schemas"]["Version"][];
        };
        /** WorkBundleResponse */
        WorkBundleResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["WorkArtifactBundleResponse"][];
            /** Jobs */
            jobs: components["schemas"]["Job"][];
            work: components["schemas"]["Work"];
        };
        /** Workflow */
        Workflow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            kind: components["schemas"]["WorkflowKind"];
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Target Version Id */
            target_version_id?: string | null;
        };
        /** WorkflowJobResponse */
        WorkflowJobResponse: {
            job: components["schemas"]["Job"];
            workflow: components["schemas"]["Workflow"];
        };
        /**
         * WorkflowKind
         * @enum {string}
         */
        WorkflowKind: "understand" | "correct" | "compare" | "create" | "export";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_ask_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_upload_api_v1_projects__project_id__artifacts_finalize_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeUploadBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_artifact_api_v1_projects__project_id__artifacts_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_artifact_api_v1_projects__project_id__artifacts_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_intent_api_v1_projects__project_id__artifacts_upload_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadIntentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_works_api_v1_projects__project_id__works_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Work"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_work_api_v1_projects__project_id__works_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Work"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_resource_api_v1_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_api_v1_versions__version_id__entities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_api_v1_versions__version_id__insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insight"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analyze_workflow_api_v1_workflows_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeWorkflowBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_compare_workflow_api_v1_workflows_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareWorkflowBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_correct_workflow_api_v1_workflows_correct_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectWorkflowBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_create_workflow_api_v1_workflows_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_score_workflow_api_v1_workflows_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreWorkflowBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_understand_workflow_api_v1_workflows_understand_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnderstandWorkflowBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_variation_workflow_api_v1_workflows_variation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariationWorkflowBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_bundle_api_v1_works__work_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkBundleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_work_api_v1_works__work_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedWorkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    measured_changes_api_v1_works__work_id__relations_measured_changes_get: {
        parameters: {
            query: {
                source_version_id: string;
            };
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasuredChangeQueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_perceptual_spans_api_v1_works__work_id__relations_perceptual_span_comparison_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerceptualSpanComparisonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerceptualSpanComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLiveResponse"];
                };
            };
        };
    };
    health_queue_health_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthQueueResponse"];
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadyResponse"];
                };
            };
        };
    };
}
