#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-full}"
PASS=0
FAIL=0
TOTAL_START=$SECONDS

pass() { PASS=$((PASS + 1)); echo "  ✅ $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  ❌ $1"; }

usage() {
  cat <<'EOF'
Usage: scripts/check.sh [full|fast|frontend|backend|e2e]

  full      Canonical local gate: build, lint, typecheck, contract/import architecture/API contracts,
            backend/frontend tests, optional backend health, and Playwright.
  fast      Inner loop: lint, typecheck, contract/import architecture/API contracts, backend/frontend tests.
            Skips production build, live health checks, and Playwright.
  frontend  Frontend lint, typecheck, import architecture, and Vitest.
  backend   Locked backend sync, Ruff, import architecture, API contract, and backend unit tests.
  e2e       Production frontend build and Playwright only.
EOF
}

case "$MODE" in
  full|fast|frontend|backend|e2e) ;;
  -h|--help|help)
    usage
    exit 0
    ;;
  *)
    echo "Unknown check mode: $MODE" >&2
    usage >&2
    exit 2
    ;;
esac

needs_backend=false
case "$MODE" in
  full|fast|backend) needs_backend=true ;;
esac

if "$needs_backend" && ! command -v uv >/dev/null 2>&1; then
  echo "uv is required for '$MODE'. Install uv 0.12.6, then rerun this command." >&2
  exit 2
fi

run_frontend_build() {
  echo ""
  echo "── Frontend build ──"
  local started=$SECONDS
  if npm run build; then
    pass "build ($((SECONDS - started))s)"
  else
    fail "build ($((SECONDS - started))s)"
  fi
}

run_frontend_static() {
  echo ""
  echo "── Frontend lint ──"
  local started=$SECONDS
  if npm run lint; then
    pass "lint ($((SECONDS - started))s)"
  else
    fail "lint ($((SECONDS - started))s)"
  fi

  echo ""
  echo "── Frontend typecheck ──"
  started=$SECONDS
  if npm run typecheck; then
    pass "typecheck ($((SECONDS - started))s)"
  else
    fail "typecheck ($((SECONDS - started))s)"
  fi
}

run_frontend_architecture() {
  echo ""
  echo "── Frontend import architecture ──"
  local started=$SECONDS
  local output_dir
  output_dir="$(mktemp -d)"
  local depcruise=(
    npx --yes
    --package=dependency-cruiser@18.2.0
    --package=typescript@5.7.3
    depcruise
  )

  if "${depcruise[@]}" \
      --config .dependency-cruiser.cjs \
      --validate \
      app components lib && \
    "${depcruise[@]}" \
      --config .dependency-cruiser.cjs \
      --output-type mermaid \
      --include-only '^(app|components|lib)/' \
      --collapse 2 \
      --output-to "$output_dir/frontend-dependencies.mmd" \
      app components lib && \
    {
      cat <<'EOF'
# Frontend dependency graph

> Generated by dependency-cruiser 18.2.0 with TypeScript 5.7.3 from `.dependency-cruiser.cjs`. Do not hand-edit this graph; regenerate it through the architecture check when frontend imports change.

This is an orientation view of `app/`, `components/`, and `lib/`. Deeper folders are collapsed to keep the graph reviewable. The architecture rules in `.dependency-cruiser.cjs`, not the picture alone, are the enforceable contract.

```mermaid
EOF
      cat "$output_dir/frontend-dependencies.mmd"
      echo '```'
    } > "$output_dir/frontend-dependencies.md" && \
    diff -u docs/generated/frontend-dependencies.md "$output_dir/frontend-dependencies.md"; then
    pass "frontend architecture ($((SECONDS - started))s)"
  else
    fail "frontend architecture ($((SECONDS - started))s)"
  fi
  rm -rf "$output_dir"
}

run_frontend_tests() {
  echo ""
  echo "── Frontend tests ──"
  local started=$SECONDS
  if npm test; then
    pass "vitest ($((SECONDS - started))s)"
  else
    fail "vitest ($((SECONDS - started))s)"
  fi
}

run_shell_static() {
  echo ""
  echo "── Shell static checks ──"
  local started=$SECONDS
  local scripts=()
  mapfile -t scripts < <(git ls-files '*.sh')
  if [ "${#scripts[@]}" -eq 0 ]; then
    pass "shellcheck (no tracked shell scripts, $((SECONDS - started))s)"
  elif uvx --from shellcheck-py==0.11.0.1 shellcheck "${scripts[@]}"; then
    pass "shellcheck ($((SECONDS - started))s)"
  else
    fail "shellcheck ($((SECONDS - started))s)"
  fi
}

run_contract_dependencies() {
  echo ""
  echo "── Focused contract dependencies ──"
  local started=$SECONDS
  if python3 scripts/test_contract_dependencies.py && \
     python3 scripts/contract_dependencies.py contract-dependencies.json; then
    pass "contract dependencies ($((SECONDS - started))s)"
  else
    fail "contract dependencies ($((SECONDS - started))s)"
  fi
}

run_backend_sync() {
  echo ""
  echo "── Locked backend environment ──"
  local started=$SECONDS
  if uv sync --project backend --locked; then
    pass "uv sync --locked ($((SECONDS - started))s)"
  else
    fail "uv sync --locked ($((SECONDS - started))s)"
  fi
}

run_backend_static() {
  echo ""
  echo "── Backend static checks ──"
  local started=$SECONDS
  if uv run --project backend --locked ruff check backend/ && \
     uv run --project backend --locked ruff format backend/ --check; then
    pass "ruff ($((SECONDS - started))s)"
  else
    fail "ruff ($((SECONDS - started))s)"
  fi

  echo ""
  echo "── Backend import architecture ──"
  started=$SECONDS
  if (cd backend && uvx --from import-linter==2.14 lint-imports --config .importlinter); then
    pass "backend architecture ($((SECONDS - started))s)"
  else
    fail "backend architecture ($((SECONDS - started))s)"
  fi

  echo ""
  echo "── Generated API contract ──"
  started=$SECONDS
  if npm run api:check; then
    pass "api contract ($((SECONDS - started))s)"
  else
    fail "api contract ($((SECONDS - started))s)"
  fi
}

run_backend_tests() {
  echo ""
  echo "── Backend tests ──"
  local started=$SECONDS
  if uv run --project backend --locked python -m pytest backend/tests/ -v \
      --durations=20 --durations-min=1.0; then
    pass "pytest ($((SECONDS - started))s)"
  else
    fail "pytest ($((SECONDS - started))s)"
  fi
}

run_backend_health() {
  echo ""
  echo "── Backend health (optional live service) ──"
  local be_url="${MUSIC_BACKEND_URL:-}"
  if [ -n "$be_url" ]; then
    local health
    local started=$SECONDS
    if health=$(curl -sf "$be_url/health/live"); then
      pass "health/live ($health, $((SECONDS - started))s)"
    else
      fail "health/live (unreachable, $((SECONDS - started))s)"
    fi
    started=$SECONDS
    if health=$(curl -sf "$be_url/health/ready"); then
      pass "health/ready ($health, $((SECONDS - started))s)"
    else
      fail "health/ready (unreachable, $((SECONDS - started))s)"
    fi
  else
    echo "  ℹ️  MUSIC_BACKEND_URL not set — live health checks not requested"
  fi
}

run_e2e() {
  echo ""
  echo "── Playwright E2E ──"
  local started=$SECONDS
  if npx playwright test --reporter=line; then
    pass "e2e ($((SECONDS - started))s)"
  else
    fail "e2e ($((SECONDS - started))s)"
  fi
}

echo "══════════════════════════════════════════"
echo "  listencloser — $MODE check"
echo "══════════════════════════════════════════"

case "$MODE" in
  full)
    run_backend_sync
    run_shell_static
    run_contract_dependencies
    run_frontend_build
    run_frontend_static
    run_frontend_architecture
    run_backend_static
    run_backend_tests
    run_frontend_tests
    run_backend_health
    run_e2e
    ;;
  fast)
    run_shell_static
    run_contract_dependencies
    run_frontend_static
    run_frontend_architecture
    run_backend_static
    run_backend_tests
    run_frontend_tests
    ;;
  frontend)
    run_frontend_static
    run_frontend_architecture
    run_frontend_tests
    ;;
  backend)
    run_backend_sync
    run_backend_static
    run_backend_tests
    ;;
  e2e)
    run_frontend_build
    run_e2e
    ;;
esac

echo ""
echo "══════════════════════════════════════════"
echo "  $PASS passed, $FAIL failed in $((SECONDS - TOTAL_START))s"
echo "══════════════════════════════════════════"
exit "$FAIL"
